angular.module("valiant.views", []).run(["$templateCache", function($templateCache) {$templateCache.put("admin.html","<div class=\"main admin\">\n    <div ui-view=\"header\" class=\"header admin-header\"></div>\n    <div ui-view=\"content\" class=\"content admin-content\"></div>\n    <div ui-view=\"footer\" class=\"footer admin-footer\"></div>\n</div>");
$templateCache.put("main.html","<div class=\"main\">\n    <div ui-view=\"header\" class=\"header main-header\"></div>\n    <div ui-view=\"content\" class=\"content main-content\"></div>\n    <div ui-view=\"footer\" class=\"footer main-footer\"></div>\n</div>");
$templateCache.put("partials/admin/home/content.html","This is the admin page!");
$templateCache.put("partials/admin/home/home.html","<div ui-view=\"content\" class=\"admin-content\"></div>");
$templateCache.put("partials/main/about/about.html","<div ui-view=\"content\" class=\"about-content\"></div>");
$templateCache.put("partials/main/about/content.html","This is about my love for my Beautiful <span ng-bind=\"name\"></span>.");
$templateCache.put("partials/main/home/content.html","This is the main page!");
$templateCache.put("partials/main/home/footer.html","<span class=\"admin-link\"><a ui-sref=\"admin.home.default\">Admin</a></span>");
$templateCache.put("partials/main/home/header.html","<div>Valiant Athletics</div>\n<a ui-sref=\"main.home.default\">Home</a>\n<a ui-sref=\"main.about.default\">About</a>\n");
$templateCache.put("partials/main/home/home.html","<div ui-view=\"content\" class=\"home-content\"></div>");}]);