angular.module("valiant.views", []).run(["$templateCache", function($templateCache) {$templateCache.put("admin.html","<div class=\"root admin\">\n    <div ui-view=\"header\" class=\"header\"></div>\n    <div ui-view=\"content\" class=\"content\"></div>\n    <div ui-view=\"footer\" class=\"footer\"></div>\n</div>");
$templateCache.put("main.html","<div class=\"root main\">\n    <div ui-view=\"header\" class=\"header\"></div>\n    <div ui-view=\"content\" class=\"content\"></div>\n    <div ui-view=\"footer\" class=\"footer\"></div>\n</div>");
$templateCache.put("modals/partials/error_modal.html","<div class=\"error-modal\">\n    <span class=\"error-modal-message\" ng-bind=errorMessage></span>\n</div>");
$templateCache.put("partials/admin/home/content.html","<span class=\"admin-text\">This is the admin page!</span>");
$templateCache.put("partials/admin/home/footer.html","<span class=\"logout-link\"><a>Logout</a></span>");
$templateCache.put("partials/admin/home/header.html","<div>Valiant Athletics Admin Page</div>\n");
$templateCache.put("partials/admin/home/home.html","<div class=\"home\">\n    <div ui-view=\"content\" class=\"content\"></div>\n</div>");
$templateCache.put("partials/main/about/about.html","<div class=\"about\">\n    <div ui-view=\"content\" class=\"content\"></div>\n</div>");
$templateCache.put("partials/main/about/content.html","<span class=\"about-text\">This is about my love for my Beautiful <span ng-bind=\"name\"></span>.</span>");
$templateCache.put("partials/main/home/content.html","<span class=\"home-text\">This is the main page!</span>");
$templateCache.put("partials/main/home/footer.html","<span class=\"admin-link\"><a ui-sref=\"admin.home.default\">Admin</a></span>");
$templateCache.put("partials/main/home/header.html","<div>Valiant Athletics</div>\n<a ui-sref=\"main.home.default\">Home</a>\n<a ui-sref=\"main.about.default\">About</a>\n");
$templateCache.put("partials/main/home/home.html","<div class=\"home\">\n    <div ui-view=\"content\" class=\"content\"></div>\n</div>");}]);